apiVersion: v1
kind: Service
metadata:
  name: orgconnect-green
  namespace: orgconnect
  labels:
    app: orgconnect
    version: green
spec:
  type: ClusterIP
  selector:
    app: orgconnect
    version: green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
  sessionAffinity: ClientIP

