apiVersion: v1
kind: Service
metadata:
  name: orgconnect-active
  namespace: orgconnect
  labels:
    app: orgconnect
  annotations:
    description: "Active service that routes to either blue or green deployment"
spec:
  type: NodePort
  selector:
    app: orgconnect
    version: blue  # Initially pointing to blue, Jenkins will switch this
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
    name: http
  sessionAffinity: ClientIP

